### ISSUE TITLE
Break the Wiki into "sections"

### ISSUE THREAD

**Issue by caranha** [iptp/Nihongo-Typing#1]
Divide the wiki into smaller, logically separated parts. 
The Main digits (1., 2., 3.,) reference branches of the code, for each milestone.
The minor digits (1.1, 1.2, 3.1) reference concepts in each branch, such as "outline"

* Ideas for main digits:
   - 1. Game Prototype
   - 2. Milestone 2 (some improvements, graphics?)
   - 3. Milestone 3
   - n. Milestone N
* Ideas for minor digits
   - 1.0 Introduction to the tutorial
   - 1.1 Idea for the program
   - 1.2 Greenfoot base classes (boilerplate)
   - 1.3 Reading the word dictionary file
   - 1.4 Displaying a word
   - 1.5 User input
   - Etc.

**Comment by tibuurcio** [comment]
Done: [Wiki page](https://github.com/iptp/Nihongo-Typing/wiki)
